campus:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: campus_aides
    username: root
    password: 123456
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: LTAI5tMGPVnrfpBAm4aJBXuK
#    access-key-secret: yk4IONdASun6jWSC8sdZWKL68pZSCJ
#    bucket-name: rzrzrz